# Generated by Django 4.2.1 on 2023-12-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='absensi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
