# Generated by Django 4.2.1 on 2023-12-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_absensi_created_at_absensi_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
