# Generated by Django 4.2.1 on 2023-12-03 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userManagement', '0003_absensi_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absensi',
            name='id_guru',
        ),
        migrations.AddField(
            model_name='absensi',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
